# for development

services:
  backend:
    build:
      context: template_app
      dockerfile: Dockerfile.local 
    container_name: django
    env_file:
      - ./template_app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./template_app:/home/appuser

  db:
    image: postgres:latest
    container_name: simple-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

