# create a dockerfile

FROM python:3.12

ARG USER_ID=1234
ARG GROUP_ID=1234

# Create group and user
RUN groupadd -g $GROUP_ID appgroup && \
    useradd -u $USER_ID -g $GROUP_ID -m appuser

WORKDIR /home/appuser

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.local.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh

EXPOSE 8000

USER appuser

ENTRYPOINT ["/home/appuser/entrypoint.sh"]

# Use below to pass arguments to the entrypoint exec
# CMD ["arg 1", "arg2"]
